sudo: required

services:
  - docker

before_install:
- docker run -d -p 27017:27017 --name mongo mongo

script:
- docker run -v $(pwd):/app --link mongo:mongo microsoft/dotnet sh -c "cd /app; dotnet restore; cd Server.Lib.Tests; dotnet test"